build:
  before:
    - apt-get update
    - apt-get install -y libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev libgl1 tesseract-ocr tesseract-ocr-swe
  runtime: python3.10
  command: uvicorn app:app --host 0.0.0.0 --port $PORT
